### ISSUE TITLE
Problemset

### ISSUE THREAD

**Issue by Alzomra** [hsuan1117/CodeforcesAPI#1]
Are you considering the implementation of  the problemset endpoint ? 
If find that it would be very useful for automated scripts (ex : discord bots).
I already have a discord bot that serves problems and gives contests for users , im currently using my own wrapper for the API
as i just recently discovered yours.
I can help with the implementation if you would like.

Thanks !

**Comment by hsuan1117** [comment]
Sorry for late reply.
That sounds great, but I don't have much time now.
I would add it in a few months, or any pull request is appreciated.
